### ISSUE TITLE
Nomad not registered as service

### ISSUE THREAD

**Issue by sloan-dog** [hashicorp-modules/hashistack-aws#19]
Issue: After running terraform init, terraform plan, and terraform apply, terraform installs the infrastructure succesfully. However, after ssh'ing into bastion host. Running `consul catalog services` does not list `nomad` as a registered service.

**Comment by bensojona** [comment]
@sloan-dog - Can you run the below commands and send a gist with the output from the commands?

1. `consul version`
1. `nomad version`
1. `sudo systemctl status consul`
1. `sudo systemctl status nomad`
1. `consul members`
1. `consul info`
1. `nomad server members`
1. `nomad node status`

**Comment by bensojona** [comment]
Duplicate - closing in favor of https://github.com/hashicorp/terraform-guides/issues/52
